### ISSUE TITLE
[FEATURE]: Right now Miro only works on GPT, and I want to it work for claude sonnet as well

### ISSUE THREAD

**Issue by Shailendra1703** [Shailendra1703/Miro#12]
**What**
Right now MIRO only works for chatGPT and I want to extend it so that it can notify for the response streaming and response ending for Claude sonnet as well

**How this will improve**
This will help people use a single extension for multiple LLMs, as Claude and GPT are the most famous ones so I am considering expanding it till that as of now.

**Describe alternatives you've considered**
Claude sonnet AI https://claude.ai/

**Comment by Kr-Adarsh** [comment]
I've got a hang of what feature you want to add, I would like to work on this. Do assign me, I'll start right up..

**Comment by Kr-Adarsh** [comment]
#13 Please look into it; I've made the necessary changes. Do let me know if there's anything to add or change.

**Comment by Shailendra1703** [comment]
> #13 Please look into it; I've made the necessary changes. Do let me know if there's anything to add or change.

Sure @Kr-Adarsh, I'll check it out, Great work btw.
