### ISSUE TITLE
[BUG]: Getting error on sendMessage function from `chrome.runtime`

### ISSUE THREAD

**Issue by Shailendra1703** [Shailendra1703/Miro#2]
Here is the screen shot of this error. Getting this error in `content.js` 

![image](https://github.com/user-attachments/assets/fe5a826f-1227-49bf-a151-6b9131b6f1ab)

**Comment by Satyasn01** [comment]
From your implementation, the error might occur if chrome.runtime.sendMessage is somehow not accessible at the time the callback runs.

Edit labels and assign if you want me to look into it

**Comment by Shailendra1703** [comment]
sure @Satyasn01, please have a look into it

**Comment by Shailendra1703** [comment]
Hello @Satyasn01, have you discovered why `sendMessage` is undefined? we can have a discussion here along with other members as well on this issue

**Comment by Satyasn01** [comment]
i'm working on it 
i'll let you know
