### ISSUE TITLE
Include CONTRIBUTING FILE AND CODE_OF_CONDUCT files 

### ISSUE THREAD

**Issue by bypratyush** [Shailendra1703/Miro#3]
I'd like to update the repository with the CONTRIBUTING file and the CODE_OF_CONDUCT file so that everyone can have a clear idea of creating forks and contributing effortlessly.

Can you please assign this task to me?

**Comment by bypratyush** [comment]
@Shailendra1703 Added the pull request for this task. Kindly review.

**Comment by Shailendra1703** [comment]
Yes @pratyush090506 , I'll surely review it in sometime and merge it.
