### ISSUE TITLE
Add favicon to the site.

### ISSUE THREAD

**Issue by Sandigupta** [Shailendra1703/Miro#8]
![icon128](https://github.com/user-attachments/assets/0ad43a12-d8fa-474a-9576-04c825963434)
The favicon image is currently not displaying on the site. I will add it to enhance the site's visibility and improve its appearance.

**Comment by Shailendra1703** [comment]
Go Ahead @Sandigupta 🚀

**Comment by Sandigupta** [comment]
@Shailendra1703 
I am doing it.
thanks
